# Based on example https://github.com/bilayer-containers/bilayers/blob/main/algorithms/cellpose_inference/config.yaml
citations:
  - name: "Empanada Segmentation"
    doi: 10.1016/j.cels.2022.12.006
    license: "BSD 3-Clause"
    description: "Panoptic segmentation algorithms for 2D and 3D electron microscopy in napari"

docker_image:
  org: cellularimagingcf
  name: empanadasegmentation
  tag: "latest"
  platform: "linux/amd64"

algorithm_folder_name: "empanadasegmentation"

exec_function: 
  name: "generate_cli_command"
  cli_command: "python wrapper.py"
  hidden_args:
    - cli_tag: "--gtfolder"
      value: "/data/gt"
      cli_order: 3
    - cli_tag: "--local"
      value: "True"
      append_value: false
      cli_order: 4

inputs:
  - name: input_images
    type: image
    label: "Input Image Directory"
    subtype: 
      - grayscale
      - color
      - binary
    description: "Path to the directory of input images"
    cli_tag: "--input_images"
    cli_order: 0
    default: "directory"
    optional: False
    format: 
      - tiff
      - ometiff
      - omezarr
    folder_name: "/input_images"
    file_count: "multiple"
    section_id: "inputs"
    mode: "beginner"
    depth: True
    timepoints: True
    tiled: True
    pyramidal: True

outputs:
  - name: segmented_labels
    type: image
    label: "Segmented Ome-zarr images"
    subtype: 
      - label
    description: "Segmented image if --save_omezarr flag is true."
    cli_tag: "--segmented_labels"
    cli_order: 0
    default: "directory"
    optional: True
    format: 
      - omezarr
    folder_name: "/output_images"
    file_count: "single"
    section_id: "outputs"
    mode: "beginner"
    depth: True
    timepoints: True
    tiled: True
    pyramidal: True

# Display_only Section
display_only:
  # dummy example : DONOT PUT CLI_TAG FLAG AT ALL. THESE ARE JUST FOR DISPLAY